### ISSUE TITLE
Register 1 initialization nibbles are flipped

### ISSUE THREAD

**Issue by sjthomsen** [RobTillaart/DAC8552#14]
should be:
  _register[0] = 0x00;
  _register[1] = 0x04;

not 
  _register[0] = 0x00;
  _register[1] = 0x40;

**Comment by RobTillaart** [comment]
Thanks for reporting
Will look into datasheet tomorrow to verify.

**Comment by RobTillaart** [comment]
From datasheet:

![image](https://github.com/RobTillaart/DAC8552/assets/462844/98f5e72c-095c-4828-88f1-cdcf69ee2b2a)

The value should indeed be 0x04 to set BUFFER_SELECT to 1. 

I will prepare a PR asap.

**Comment by RobTillaart** [comment]
PR made, build is running.

**Comment by RobTillaart** [comment]
@sjthomsen 

Build is successful, does the library work as expected after your fix?
Or are there things missing (that could easily be included) ?

Thanks again for finding the bug!

**Comment by sjthomsen** [comment]
Works great.  Sorry for the delayed response.  Busy weekend and wasn't able to check it until today.

**Comment by RobTillaart** [comment]
No problem, I rechecked changes after a good nights rest and it still made sense soI merged it.

Thanks again for reporting the bug!
