### ISSUE TITLE
SPI Compile Issue with Pi Pico/Arduino MBED

### ISSUE THREAD

**Issue by sjthomsen** [RobTillaart/DAC8552#18]
I have an issue where the Platform.IO uses the "framework-arduino-mbed" libraries which does not have a definition for SPIClassRP2040.

Instead, just using the regular old SPIClass works just fine with a Pi Pico but I have to manually make that change to the DAC8552.h.  Is it possible to use SPIClass or is SPIClassRP2040 necessary for some applications?

Thanks,
Samuel Thomsen

**Comment by RobTillaart** [comment]
Thanks Samuel for your question, it is a good one.

For the RP2040 there are different compiler environments, and I have one that uses the SPIClassRP2040. 

The solution would be to extend the conditional in the .h file, however I have no time to dive into it coming days.

```cpp
#ifndef __SPI_CLASS__
  #if defined(ARDUINO_ARCH_RP2040)      <<<  and not defined MBED something
  #define __SPI_CLASS__   SPIClassRP2040
  #else
  #define __SPI_CLASS__   SPIClass
  #endif
#endif
```

Can you post a few lines of your compiler output to see if there is a define that flags "framework-arduino-mbed" ?

**Comment by sjthomsen** [comment]
Here is the compiler output for DAC8552.cpp
`arm-none-eabi-g++ -o .pio\build\pi_pico\lib539\DAC8552\DAC8552.cpp.o -c -Wvla -fno-rtti -std=gnu++14 -DMBED_TRAP_ERRORS_ENABLED=1 -Os -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -c -fdata-sections -ffunction-sections -fmessage-length=0 -fno-exceptions -fomit-frame-pointer -funsigned-char -mcpu=cortex-m0plus -mthumb -iprefixC:\Users\samuel.thomsen\.platformio\packages\framework-arduino-mbed\cores\arduino @C:\Users\samuel.thomsen\.platformio\packages\framework-arduino-mbed\variants\RASPBERRY_PI_PICO\includes.txt -nostdlib -DPLATFORMIO=60115 -DARDUINO_RASPBERRY_PI_PICO -DARDUINO_ARCH_RP2040 -DARM_MATH_CM0PLUS -D__CMSIS_RTOS -DCOMPONENT_FLASHIAP=1 -D__CORTEX_M0PLUS -DDEVICE_ANALOGIN=1 -DDEVICE_FLASH=1 -DDEVICE_I2C=1 -DDEVICE_I2CSLAVE=1 -DDEVICE_INTERRUPTIN=1 -DDEVICE_PORT_IN=1 -DDEVICE_PORT_OUT=1 -DDEVICE_PWMOUT=1 -DDEVICE_RESET_REASON=1 -DDEVICE_RTC=1 -DDEVICE_SERIAL=1 -DDEVICE_SERIAL_FC=1 -DDEVICE_SPI=1 -DDEVICE_USBDEVICE=1 -DDEVICE_USTICKER=1 -DDEVICE_WATCHDOG=1 -D__MBED__=1 -DMBED_BUILD_TIMESTAMP=1707125159.6448777 -D__MBED_CMSIS_RTOS_CM -DMBED_MPU_CUSTOM -DMBEDTLS_ENTROPY_NV_SEED -DPICO_NO_BINARY_INFO=1 -DPICO_ON_DEVICE=1 -DPICO_RP2040_USB_DEVICE_ENUMERATION_FIX=1 -DPICO_TIME_DEFAULT_ALARM_POOL_DISABLED -DPICO_UART_ENABLE_CRLF_SUPPORT=0 -DTARGET_CORTEX -DTARGET_CORTEX_M -DTARGET_LIKE_CORTEX_M0 -DTARGET_LIKE_MBED -DTARGET_M0P -DTARGET_memmap_default -DTARGET_NAME=RASPBERRY_PI_PICO -DTARGET_RASPBERRYPI -DTARGET_RASPBERRY_PI_PICO -DTARGET_RELEASE -DTARGET_RP2040 -DTOOLCHAIN_GCC -DTOOLCHAIN_GCC_ARM -DMBED_NO_GLOBAL_USING_DIRECTIVE=1 -DCORE_MAJOR=4 -DCORE_MINOR=1 -DCORE_PATCH=1 -DUSE_ARDUINO_PINOUT -DARDUINO=10810 -DARDUINO_ARCH_MBED -I.pio\libdeps\pi_pico\DAC8552 -IC:\Users\samuel.thomsen\.platformio\packages\framework-arduino-mbed\libraries\SPI -IC:\Users\samuel.thomsen\.platformio\packages\framework-arduino-mbed\cores\arduino -IC:\Users\samuel.thomsen\.platformio\packages\framework-arduino-mbed\cores\arduino\api\deprecated -IC:\Users\samuel.thomsen\.platformio\packages\framework-arduino-mbed\cores\arduino\api\deprecated-avr-comp -IC:\Users\samuel.thomsen\.platformio\packages\framework-arduino-mbed\variants\RASPBERRY_PI_PICO .pio\libdeps\pi_pico\DAC8552\DAC8552.cpp`

I think maybe the best option might be '-DARDUINO_ARCH_MBED'

**Comment by RobTillaart** [comment]
Thanks, that could work

Can you replace the "define section" in the .h file and test it

```cpp
#ifndef __SPI_CLASS__
  #if defined(ARDUINO_ARCH_MBED)
  #define __SPI_CLASS     SPIClass
  #elif defined(ARDUINO_ARCH_RP2040)
  #define __SPI_CLASS__   SPIClassRP2040
  #else
  #define __SPI_CLASS__   SPIClass
  #endif
#endif
```

I'll prepare a new PR.

**Comment by sjthomsen** [comment]
Appears to work for both my pico and a regular nano board.

**Comment by RobTillaart** [comment]
Merged solution into master,
thanks for testing!

**Comment by RobTillaart** [comment]
@sjthomsen 
updated the DAC8550/1/4 libraries too

**Comment by sjthomsen** [comment]
Awesome!  Haven't used those libraries yet but good to know they're ready.

Thanks again!

**Comment by RobTillaart** [comment]
some 20 libraries to go :)
