### ISSUE TITLE
Any test with the DAC8562?

### ISSUE THREAD

**Issue by edwardocano** [RobTillaart/DAC8552#20]
Anybody has tested this library with the DAC8562?

**Comment by RobTillaart** [comment]
What is the actual problem with the library you want to report?

**Comment by RobTillaart** [comment]
@edwardocano 

Hi,

Downloaded the datasheet and a quick check gave me at least the following differences on hardware level
- dac8562 has a gain register
- dac8562 has a 2.5V reference 
- dac8562 has an LDAC line => the lib wont support this (async modus)
- dac8562 has an CLR line => the lib wont support this (async modus)

Looking at the bit streams to address the DAC, these are not compatible specifically in the control bits.

So the DAC8562 will not work with this library, 

Rob

**Comment by edwardocano** [comment]
Thank you so much for the information, i had being trying to use the DAC8562 but i can not make it work yet.

**Comment by RobTillaart** [comment]
@edwardocano 
I have a library for the DAC8560 which is a single channel DAC from the same series.
If you can give that a try as that might work on one channel.
The DAC8560 lib could be a starting point for a DAC8562 library (somewhere in the future when time permits)

update:
The setValue() function uses same bit pattern,

**Comment by edwardocano** [comment]
@RobTillaart Thanks for your help. Between the components dac8560 and dac8550 do you see a big improvement?

**Comment by RobTillaart** [comment]
> Thanks for your help. Between the components dac8560 and dac8550 do you see a big improvement?

A quick look at the datasheets and the only thing I see is the DAC8560 has an internal Vref of 2.5 volt.
This can be valuable.
They look pin compatible.
Did not check the protocol details (obvious the DAC8550 has no internal Vref functions).
