### ISSUE TITLE
Esp32WROOM32 restarts

### ISSUE THREAD

**Issue by edwardocano** [RobTillaart/DAC8552#21]
I am trying to run the examples in a esp32 but with all the examples the esp32 only restarts.  the library also supports esp32?

**Comment by edwardocano** [comment]
I added a code to know the reason of the reset and only shows this.

```
rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4832
load:0x40078000,len:16460
load:0x40080400,len:4
load:0x40080404,len:3504
entry 0x400805cc
C:\Users\kno_2\OneDrive\Escritorio\DAC8552-master\examples\DAC8552_same_time_write\DAC8552_same_time_write.ino
DAC8552_LIB_VERSION: 0.5.1
Reset Reason: Interrupt Watchdog Reset
```

update for readability

**Comment by RobTillaart** [comment]
Thanks for reporting the issue,
I have no hardware to verify, but I will investigate coming days.
There are (closed) issues of people who worked with it with ESP32 so it should be possible to get it to work.
I have a hypothesis why it failed but I have to do some digging if details match.

Have you tried the library with software SPI ? 
Replacing the constructor call in the examples just define three pins.
**DAC8552(uint8_t select, uint8_t spiData, uint8_t spiClock) Constructor SW SPI.**

**Comment by RobTillaart** [comment]
> rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)

The sketch uses pin 10 as select which 
```DAC8552 mydac(10);```

This pin is used by the FLASH RAM (pin 6-11) on ESP32, and is free for other boards.
So changing the pin to a free one should get it working.

Please let me know.

**Comment by edwardocano** [comment]
Yes the problem was the CS pin, I connected to the default pins but the code override the CS to the pin 10 and that pin can not be used.

**Comment by edwardocano** [comment]
One more question, I am checking the same_time_write example and I can see first buffer for example the channel A, after that set the Value for channel B, when you set a value in any channel all the channels are updated?.

**Comment by RobTillaart** [comment]
I need to check the data sheet / code on that one as I do not have all details of all libraries in my head.

Ps
Can you confirm that the SWSPI worked on ESP32?

**Comment by RobTillaart** [comment]
> when you set a value in any channel all the channels are updated?.

Yes, that is how it should work.

**Comment by RobTillaart** [comment]
@edwardocano 

Can you confirm that the SWSPI worked on ESP32?

**Comment by edwardocano** [comment]
Sorry i was checking several speeds and pins, everything looks right also for SWSPI, the only thing i think could improve is DMA but this is specific for esp32.

**Comment by RobTillaart** [comment]
Thanks for confirming SWSPI.

DMA sounds interesting, do you have any idea how much faster it is.

Do you have a link to some tutorials explaining the pro and cons of DMA?

Is the DMA interface compatible with ESP32?

**Comment by RobTillaart** [comment]
@edwardocano 

Closed the issue as it seems solved.
