### ISSUE TITLE
Add DMA support for the ESP32

### ISSUE THREAD

**Issue by unwndevices** [RobTillaart/DAC8552#8]
SPI transfers are not the best thing on the ESP32, DMA should help relieve the MCU from much of the work.
I tried implementing it for this library with not much luck, I'm still a newbie.

**Comment by RobTillaart** [comment]
Hi @unwndevices 

Currently quite busy with upgrading build system for all the libraries, soon licenses need updates for 2022, and many minor updates I try to do in the winter.

Never did DMA on ESP32 either so I need to investigate how DMA works on the ESP32, and HOW it can be used from within a library. That will take many weeks (given my agenda) and an outcome may be a dedicated DAC8552_ESP32 library.

So not on short term, but request is noticed.

**Comment by unwndevices** [comment]
@RobTillaart no worries, It works fine for me in its actual state, I got intrigued reading about DMA and wanted to try it myself, looking forward to study your code!

**Comment by RobTillaart** [comment]
not investigated, just to keep the link - https://github.com/hideakitai/ESP32DMASPI

**Comment by unwndevices** [comment]
there's also this example directly from espressif - [https://github.com/espressif/esp-idf/blob/master/examples/peripherals/spi_master/lcd/main/spi_master_example_main.c](https://github.com/espressif/esp-idf/blob/master/examples/peripherals/spi_master/lcd/main/spi_master_example_main.c)

**Comment by RobTillaart** [comment]
> there's also this example directly from espressif - https://github.com/espressif/esp-idf/blob/master/examples/peripherals/spi_master/lcd/main/spi_master_example_main.c

(definitely not understood all immediately )  Looks like DMA is more suitable when you need to transfer large blocks. 
The DAC returns 16 bits so a question that arises is if DMA is faster or looses the gain in overhead?

How much samples per second does your application need?

**Comment by unwndevices** [comment]
@RobTillaart I would need 44100 sample per second. I thought a solution to free the cpu from the transactions would be to treat the dac as an i2s device (without the L/R clock) and use ESP32's I2S implementation (i2s_config) , where you write to the dma buffer and the dma controller does the transactions in the background

**Comment by RobTillaart** [comment]
@unwndevices 
Two threads could also be an option then. 
An ESP32 has 2 cores and use one core doing the sampling to a shared buffer and the other could send it to wherever. 

At 5V a clock pulse could be as short as 33 ns according to the datasheet. 
That would allow 30MHz so transfer about a million samples per second => order of microseconds.

Settling Time: 10ms to ±0.003% FSR
So the sensor can take roughly 100K samples per second, so the 44100 should be possible.
However if you want stereo it might be better to use a separate DAC per channel.
(just some thoughts)

**Comment by RobTillaart** [comment]
mmm, I have no example code for performance measurement. 
If you happen to write such sketch I am interested to add it to the repo.

**Comment by RobTillaart** [comment]
@unwndevices 

Any progress to report ?

Wrote a minimal performance test and ran it on an UNO and an ESP32.
An ESP32 could write ~100 K values per second. (sawtooth test)

```cpp
//
//    FILE: DAC8552_sw_spi_performance.ino
//  AUTHOR: Rob Tillaart
// PURPOSE: DAC8552 performance with software SPI
//     URL: https://github.com/RobTillaart/DAC8552
//
//  measurements full speed sawtooth
//            UNO               ESP32
//            us   KHz          us   KHz
// --------------------------------------------
//   SWSPI    328   3.048       10   100.000
//   HWSPI     22  45.000       11    90.000

#include "DAC8552.h"

DAC8552 mydac(12, 13, 14);   // SW SPI
// DAC8552 mydac(10);   // HW SPI

uint16_t value = 0;
uint32_t start, stop;

void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);
  Serial.println(DAC8552_LIB_VERSION);
  mydac.begin();
}

void loop()
{
  // simulate fast sawtooth;
  start = micros();
  mydac.setValue(0, value);
  stop = micros();
  value++;
  Serial.println(stop - start);
  delay(500);
}
```

I'll add this example to the master branch (no new release for this)

**Comment by unwndevices** [comment]
Hey @RobTillaart I quickly tested the i2s interface emulating an spi transfer, it works, and it's pretty fast too! I got 7us (~140Khz). I still have to test what all i2s configs do, but here's the test I did(it's pretty raw, I quickly edited an i2s example code) 
```cpp
// Includes
#include <Arduino.h>
#include "pinout.h"
#include "driver/i2s.h"

uint16_t _value;
uint16_t _register;
uint32_t timer;
uint32_t value24Bit; // This holds the value we actually send to the I2S buffers, it basically
uint16_t increment = 0;
static const i2s_port_t i2s_num = I2S_NUM_0; // i2s port number

// I2S configuration structures

static const i2s_config_t i2s_config = {
    .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX),
    .sample_rate = 48000,
    .bits_per_sample = I2S_BITS_PER_SAMPLE_24BIT,
    .channel_format = I2S_CHANNEL_FMT_ONLY_LEFT,
    .communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_MSB),
    .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1, // high interrupt priority
    .dma_buf_count = 2,                       // 4 buffers
    .dma_buf_len = 64,
    .use_apll = 0,
    .tx_desc_auto_clear = true,
    .fixed_mclk = -1};

// These are the physical wiring connections to our I2S decoder board/chip from the esp32, there are other connections
// required for the chips mentioned at the top (but not to the ESP32), please visit the page mentioned at the top for
// further information regarding these other connections.

static const i2s_pin_config_t pin_config = {
    .bck_io_num = DAC_SCLK,          // The bit clock connectiom, goes to pin 27 of ESP32
    .ws_io_num = DAC_SS,             // Word select, also known as word select or left right clock
    .data_out_num = DAC_DIN,         // Data out from the ESP32, connect to DIN on 38357A
    .data_in_num = I2S_PIN_NO_CHANGE // we are not interested in I2S data into the ESP32
};

//------------------------------------------------------------------------------------------------------------------------

void setup()
{
  i2s_driver_install(i2s_num, &i2s_config, 0, NULL); // ESP32 will allocated resources to run I2S
  i2s_set_pin(i2s_num, &pin_config);                 // Tell it the pins you will be using

  _register = 0x30;
}

void loop()
{
  size_t BytesWritten; // Returned by the I2S write routine, we are not interested in it but
                       // must supply it as a param to the routine.
  _value = increment++;
  value24Bit = (_register << 24) | (_value << 8);
  timer = micros();
  i2s_write(i2s_num, &value24Bit, 4, &BytesWritten, portMAX_DELAY);
  timer = micros() - timer;
  if (!increment % 64)
  {
    log_d("%d", timer);
  }
}
```

**Comment by RobTillaart** [comment]
Quite specific and well done!

Next  step might be to use a buffer[] e.g with a sinus wave coded in it and send it over and over again

**Comment by RobTillaart** [comment]
@unwndevices 
As I will not work on this DMA topic soon, I close the issue.
Feel free to post progress as it is technically still interesting.
